-- MySQL Script generated by MySQL Workbench
-- 07/11/15 10:59:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema copa_america
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `copa_america` ;

-- -----------------------------------------------------
-- Schema copa_america
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `copa_america` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE `copa_america` ;

-- -----------------------------------------------------
-- Table `copa_america`.`PAIS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_america`.`PAIS` ;

CREATE TABLE IF NOT EXISTS `copa_america`.`PAIS` (
  `id_pais` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `capital` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_pais`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_america`.`EQUIPO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_america`.`EQUIPO` ;

CREATE TABLE IF NOT EXISTS `copa_america`.`EQUIPO` (
  `id_equipo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_pais` INT NOT NULL COMMENT '',
  `grupo` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_equipo`)  COMMENT '',
  CONSTRAINT `fk_EQUIPO_PAIS`
    FOREIGN KEY (`id_pais`)
    REFERENCES `copa_america`.`PAIS` (`id_pais`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_america`.`TIPO_PARTICIPANTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_america`.`TIPO_PARTICIPANTE` ;

CREATE TABLE IF NOT EXISTS `copa_america`.`TIPO_PARTICIPANTE` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_tipo`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_america`.`PARTICIPANTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_america`.`PARTICIPANTE` ;

CREATE TABLE IF NOT EXISTS `copa_america`.`PARTICIPANTE` (
  `id_participante` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_equipo` INT NULL COMMENT '',
  `id_tipo` INT NOT NULL COMMENT '',
  `nombre_1` VARCHAR(45) NOT NULL COMMENT '',
  `nombre_2` VARCHAR(45) NULL COMMENT '',
  `apellido_paterno` VARCHAR(45) NOT NULL COMMENT '',
  `apellido_materno` VARCHAR(45) NULL COMMENT '',
  `edad` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_participante`)  COMMENT '',
  CONSTRAINT `fk_PARTICIPANTE_EQUIPO1`
    FOREIGN KEY (`id_equipo`)
    REFERENCES `copa_america`.`EQUIPO` (`id_equipo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PARTICIPANTE_TIPO_PARTICIPANTE1`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `copa_america`.`TIPO_PARTICIPANTE` (`id_tipo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_america`.`CIUDAD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_america`.`CIUDAD` ;

CREATE TABLE IF NOT EXISTS `copa_america`.`CIUDAD` (
  `id_ciudad` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_pais` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_ciudad`)  COMMENT '',
  CONSTRAINT `fk_CIUDAD_PAIS1`
    FOREIGN KEY (`id_pais`)
    REFERENCES `copa_america`.`PAIS` (`id_pais`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_america`.`ESTADIO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_america`.`ESTADIO` ;

CREATE TABLE IF NOT EXISTS `copa_america`.`ESTADIO` (
  `id_estadio` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_ciudad` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `capacidad_espectador` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_estadio`)  COMMENT '',
  CONSTRAINT `fk_ESTADIO_CIUDAD1`
    FOREIGN KEY (`id_ciudad`)
    REFERENCES `copa_america`.`CIUDAD` (`id_ciudad`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_america`.`RONDA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_america`.`RONDA` ;

CREATE TABLE IF NOT EXISTS `copa_america`.`RONDA` (
  `id_ronda` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `cantidad_equipos` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_ronda`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_america`.`ENTRADA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_america`.`ENTRADA` ;

CREATE TABLE IF NOT EXISTS `copa_america`.`ENTRADA` (
  `id_entrada` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_ronda` INT NOT NULL COMMENT '',
  `valor` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_entrada`)  COMMENT '',
  CONSTRAINT `fk_ENTRADA_RONDA1`
    FOREIGN KEY (`id_ronda`)
    REFERENCES `copa_america`.`RONDA` (`id_ronda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_america`.`PARTIDO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_america`.`PARTIDO` ;

CREATE TABLE IF NOT EXISTS `copa_america`.`PARTIDO` (
  `id_partido` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `id_equipo` INT NOT NULL COMMENT '',
  `id_equipo1` INT NOT NULL COMMENT '',
  `id_ronda` INT NOT NULL COMMENT '',
  `id_estadio` INT NOT NULL COMMENT '',
  `gol_local` INT NULL COMMENT '',
  `gol_visita` INT NULL COMMENT '',
  `fecha` DATE NULL COMMENT '',
  `hora` TIME NULL COMMENT '',
  PRIMARY KEY (`id_partido`)  COMMENT '',
  CONSTRAINT `fk_PARTIDO_EQUIPO1`
    FOREIGN KEY (`id_equipo`)
    REFERENCES `copa_america`.`EQUIPO` (`id_equipo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PARTIDO_EQUIPO2`
    FOREIGN KEY (`id_equipo1`)
    REFERENCES `copa_america`.`EQUIPO` (`id_equipo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PARTIDO_RONDA1`
    FOREIGN KEY (`id_ronda`)
    REFERENCES `copa_america`.`RONDA` (`id_ronda`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PARTIDO_ESTADIO1`
    FOREIGN KEY (`id_estadio`)
    REFERENCES `copa_america`.`ESTADIO` (`id_estadio`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `copa_america`.`PARTICIPO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `copa_america`.`PARTICIPO` ;

CREATE TABLE IF NOT EXISTS `copa_america`.`PARTICIPO` (
  `id_participante` INT NOT NULL COMMENT '',
  `id_partido` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_participante`, `id_partido`)  COMMENT '',
  CONSTRAINT `fk_PARTICIPANTE_has_PARTIDO_PARTICIPANTE1`
    FOREIGN KEY (`id_participante`)
    REFERENCES `copa_america`.`PARTICIPANTE` (`id_participante`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_PARTICIPANTE_has_PARTIDO_PARTIDO1`
    FOREIGN KEY (`id_partido`)
    REFERENCES `copa_america`.`PARTIDO` (`id_partido`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
